#! /usr/bin/env sh
#
#  this script is intended to make it easy to run the tests inside a
#  docker container by running something like this on the host:
#
#    docker run -it flavorjones/gitter-notification-resource /work/run-tests
#
set -eux
cat /etc/alpine-release
cd /work
rake test
