#! /usr/bin/env ruby

require "json"
require_relative "lib/webhook-notification-resource"

config = JSON.parse(STDIN.read)

puts WebhookNotificationResource.new(config["source"]).out(config["params"]).to_json

exit 0
